# Generated by Django 4.1.1 on 2023-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('course_report', 'отчет о направлениях'), ('groups_report', 'отчет о группах')], default='course_report', max_length=50, verbose_name='Тип отчета')),
                ('status', models.CharField(choices=[('created', 'создан'), ('processed', 'обрабатывается'), ('falied', 'завершен с ошибкой'), ('completed', 'завершен успешно')], default='created', max_length=50, verbose_name='Статус отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Ссылка на скачивание')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'created'), ('status', 'processed'), _connector='OR'), fields=('type',), name='unique_status_type'),
        ),
    ]
